### ISSUE TITLE
Malicious inputs are not sanitized when using [align]

### ISSUE THREAD

**Issue by heikobornholdt** [cpjolicoeur/bb-ruby#25]
Hi Craig :smiley: ,

malicious inputs are not sanitized when using align-tag.

The input
````
[align=left css-selector]sadsad[/align]
````
results in
````
    <span class="bb-ruby_align_left css-selector" style="float:left css-selector;">sadsad</span>
````

That means, I can pass every css selector which can results in a destroyed page layout.

**Comment by cpjolicoeur** [comment]
closing due to lack of follow-up
