### ISSUE TITLE
Petition: html to bbcode ?¿

### ISSUE THREAD

**Issue by adriandelarco** [cpjolicoeur/bb-ruby#42]
Hello! Congratulations for this awesome gem :)

Would it be possible to perform also the inverse operation? Transform from html to bbcode?

I would like to save the object in the db with html tags. Because I suppose is more efficient to convert the bbcode to html just one time before creating the model, that everytime that someone load it. The problem is when I try to edit that object, now the content is in html, but the editor works with bbcode. 

Maybe there is a better way to do this, instead of save the content in the db with html, but if not this could be a desirable function for a lot of people.

**Comment by cpjolicoeur** [comment]
Sure, we could make code to reverse.

I think a way you can easily accomplish this though is to store both the BBCode and the transformed HTML in the DB.  You can easily select out and display the HTML version, and when you need to edit you can select out the BBCode and show that in an editor.  Then on update/save, just update both columns.

**Comment by adriandelarco** [comment]
Yes. I already thought about that.  I will  implement that solution then.

Thank you!
